### ISSUE TITLE
Upgraded to 1.5.1 from 1.4.1, lost ability to find Industrial Foregoing gear in Refined Storage

### ISSUE THREAD

**Issue by VorpalLemur** [FTBTeam/FTB-Presents-Direwolf20-1.16#163]
* **Modpack Version**: 1.5.1 (singleplayer)

* **Issue**:  This is a weirdly specific issue that has me scratching my head so please bear with me.   I upgraded to v1.5.1 and now for whatever reason I can't successfully search, by mod, for any Industrial Foregoing equipment in my Refined Storage system.   The gear is there.  If I search by name, say, I search "fluid" in RS, I see that I have 3 IF Fluid Extractors.   But if I search for @industrial or @foregoing or anything, I can't find them.  So far this only seems to affect Industrial Foregoing.  If I search for @flux, I see my flux networks gear.  If I search for @immer I see Immersive Engineering, @astr shows me Astral Sorcery.... so far everything else I've tried seems to work fine, but if I search for @indus, nothing.    
* What makes this particularly odd is that I haven't noticed either Industrial Foregoing or Refined Storage receiving an update in the changelog. 
* Even stranger, searching by mod for Industrial Foregoing in JEI works just fine.   If I type @indus in my RS search box (and have search set to JEI syncronized), I'll see Industrial Foregoing gear in the JEI pane fine... but my inventory will show as empty despite having a fair number of IF items in my inventory (as well as IF autocrafting recipes).  I can even craft new IF items and deposit them in my storage and can't find them again unless I search them by name.   My Refined Storage system now seems to have a very very specific blindspot that only manifested itself after the recent update.   I'm at a loss to explain it.
* I've tried exiting entirely, client and server and booting back up... same issue. 

* **Is it Repeatable?**: yes
* **Mod/s Affected**: Industrial Foregoing, Refined Storage

![Screen Shot 2021-01-27 at 9 27 32 AM](https://user-images.githubusercontent.com/16469763/106030325-ed689080-6082-11eb-805f-5b1a1a222dce.png)

**Comment by VorpalLemur** [comment]
![Uploading Screen Shot 2021-01-27 at 9.43.13 AM.png…]()

**Comment by VorpalLemur** [comment]
![Screen Shot 2021-01-27 at 9 43 13 AM](https://user-images.githubusercontent.com/16469763/106031565-471d8a80-6084-11eb-9e37-0f37da3e43cf.png)

**Comment by Sunekaer** [comment]
please test with 1.6.0

**Comment by SonicSpeedster16** [comment]
This has been fixed in a newer release of Refined Storage:

https://github.com/refinedmods/refinedstorage/issues/2799

**Comment by VorpalLemur** [comment]
Still experiencing the issue (at least partially) in 1.6.0.   @indust shows me a few select items:

- black hole tanks
- the Industrial Foregoing manual
- bucket of latex
- bucket of Essence

I have a lot more Industrial Foregoing in my inventory than that.   I can see it (along with all my pneumaticraft stuff) if I search for @:  instead of @indust

I'm using Refined Storage 1.9.11, latest is 1.9.12, so maybe 1.9.12 resolves it? *shrug*
